(()=>{
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let examId='test1', sectionFilter='ALL', seconds=0, timerHandle=null, theoryId=window.THEORY_TOPICS[0].id;
const state={test1:{answers:{},flags:new Set(),submitted:false},test2:{answers:{},flags:new Set(),submitted:false},practice:{}};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9%]+/g,' ').trim();
function nav(page){$$('.mainnav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$$('.page').forEach(p=>p.classList.toggle('active',p.id===page+'Page'));if(page==='answers')renderAnswerKey();}
function initNav(){$$('.mainnav button').forEach(b=>b.onclick=()=>nav(b.dataset.page));}
function setExam(id){examId=id;sectionFilter='ALL';$$('.test-card').forEach(c=>c.classList.toggle('active',c.dataset.test===id));resetTimer(false);renderExam();}
function formatTime(){const m=Math.floor(seconds/60),s=seconds%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
function resetTimer(start=true){clearInterval(timerHandle);seconds=window.EXAMS[examId].duration*60;const t=$('#timerText');if(t)t.textContent=formatTime();if(start)timerHandle=setInterval(()=>{seconds=Math.max(0,seconds-1);if($('#timerText'))$('#timerText').textContent=formatTime();if(seconds===0)clearInterval(timerHandle);},1000);}
function answerVal(q){return state[examId].answers[q.id]??'';}
function passageHtml(p){if(!p)return'';return `<div class="passage"><h5>${esc(p.title)}</h5>${esc(p.text).replace(/\n\n/g,'</p><p>').replace(/^/,'<p>').replace(/$/,'</p>')}</div>`;}
function renderQuestion(q){const val=answerVal(q), submitted=state[examId].submitted;let input='';if(q.type==='mcq'){input=`<div class="options">${q.options.map((o,i)=>{const L='ABCD'[i];return `<label class="option"><input type="radio" name="q_${q.id}" value="${L}" ${val===L?'checked':''} ${submitted?'disabled':''}><b>${L}.</b><span>${esc(o)}</span></label>`}).join('')}</div>`}else{input=q.type==='long'?`<textarea class="textanswer" data-q="${q.id}" placeholder="Viết câu trả lời của bạn…" ${submitted?'disabled':''}>${esc(val)}</textarea>`:`<input class="textanswer" data-q="${q.id}" value="${esc(val)}" placeholder="Nhập câu trả lời…" ${submitted?'disabled':''}>`;}
let fb='';if(submitted){let cls='info',head='Đáp án tham khảo';if(q.type==='mcq'){const ok=val===q.answer;cls=ok?'good':'bad';head=ok?'✓ Chính xác':`✗ Đáp án đúng: ${q.answer}`;} else if(q.type==='text'){const sc=scoreText(q,val);cls=sc.ratio>=.8?'good':sc.ratio>=.4?'info':'bad';head=`Đối chiếu: ${Math.round(sc.ratio*100)}% từ khóa chính`;}fb=`<div class="feedback show ${cls}"><b>${head}</b><div>${esc(q.explainVi)}</div>${q.model?`<div class="model"><b>Model answer:</b><br>${esc(q.model)}</div>`:''}</div>`;}
return `<article class="question" id="q-${q.id}" data-section="${q.section}"><div class="qhead"><div><span class="qnum">Question ${q.id}</span> <span class="marks">${q.marks||1} mark${(q.marks||1)>1?'s':''}</span></div><button class="flag" data-flag="${q.id}" title="Đánh dấu">${state[examId].flags.has(q.id)?'⭐':'☆'}</button></div>${passageHtml(q.passage)}<div class="stem">${esc(q.stem)}</div>${input}${fb}</article>`;}
function scoreText(q,val){const n=norm(val);if(!n)return{ratio:0,score:0};if(q.accepted?.length){const ok=q.accepted.some(a=>n===norm(a)||n.includes(norm(a)));if(ok)return{ratio:1,score:q.marks||0};}
const keys=q.keywords||[];if(!keys.length)return{ratio:0,score:0};const hit=keys.filter(k=>n.includes(norm(k))).length;const ratio=hit/keys.length;return{ratio,score:(q.marks||0)*ratio};}
function calcResult(){const ex=window.EXAMS[examId];let got=0,total=0,answered=0;ex.questions.forEach(q=>{total+=q.marks||0;const v=answerVal(q);if(String(v).trim())answered++;if(q.type==='mcq'){if(v===q.answer)got+=q.marks||0}else got+=scoreText(q,v).score;});return{got,total,answered,count:ex.questions.length};}
function renderExam(){const ex=window.EXAMS[examId];$('#examTitle').textContent=ex.title;$('#examSubtitle').textContent=ex.subtitle;$('#sourceNote').textContent=ex.sourceNote;$('#sectionSegments').innerHTML=`<button data-sec="ALL" class="${sectionFilter==='ALL'?'active':''}">Tất cả</button>`+ex.sections.map(([id,n])=>`<button data-sec="${id}" class="${sectionFilter===id?'active':''}">${esc(n)}</button>`).join('');
const qs=sectionFilter==='ALL'?ex.questions:ex.questions.filter(q=>q.section===sectionFilter);$('#questions').innerHTML=qs.map(renderQuestion).join('');
$('#palette').innerHTML=ex.questions.map(q=>`<button class="qdot ${answerVal(q)?'answered':''} ${state[examId].flags.has(q.id)?'flagged':''}" data-jump="${q.id}">${q.id}</button>`).join('');
const r=calcResult();$('#resultBox').classList.toggle('show',state[examId].submitted);if(state[examId].submitted)$('#resultBox').innerHTML=`<div><span>Điểm ước tính</span><strong>${r.got.toFixed(1)}/${r.total}</strong></div><div><span>Đã trả lời</span><strong>${r.answered}/${r.count}</strong></div><div><span>Thời gian còn lại</span><strong>${formatTime()}</strong></div><div><span>Chế độ</span><strong>Đã nộp</strong></div>`;
bindExam();}
function bindExam(){$$('#sectionSegments button').forEach(b=>b.onclick=()=>{sectionFilter=b.dataset.sec;renderExam();});$$('input[type=radio][name^=q_]').forEach(i=>i.onchange=()=>{const id=i.name.slice(2);state[examId].answers[id]=i.value;renderPaletteOnly();});$$('.textanswer').forEach(i=>i.oninput=()=>{state[examId].answers[i.dataset.q]=i.value;renderPaletteOnly();});$$('[data-flag]').forEach(b=>b.onclick=()=>{const id=b.dataset.flag;state[examId].flags.has(id)?state[examId].flags.delete(id):state[examId].flags.add(id);b.textContent=state[examId].flags.has(id)?'⭐':'☆';renderPaletteOnly();});$$('[data-jump]').forEach(b=>b.onclick=()=>{const id=b.dataset.jump;if(sectionFilter!=='ALL'&&!window.EXAMS[examId].questions.find(q=>q.id===id&&q.section===sectionFilter)){sectionFilter='ALL';renderExam();setTimeout(()=>$('#q-'+CSS.escape(id))?.scrollIntoView({behavior:'smooth',block:'start'}),40)}else $('#q-'+CSS.escape(id))?.scrollIntoView({behavior:'smooth',block:'start'});});$('#submitExam').onclick=()=>{state[examId].submitted=true;clearInterval(timerHandle);renderExam();window.scrollTo({top:$('#examArea').offsetTop-80,behavior:'smooth'});};}
function renderPaletteOnly(){const ex=window.EXAMS[examId];$('#palette').innerHTML=ex.questions.map(q=>`<button class="qdot ${answerVal(q)?'answered':''} ${state[examId].flags.has(q.id)?'flagged':''}" data-jump="${q.id}">${q.id}</button>`).join('');$$('[data-jump]').forEach(b=>b.onclick=()=>$('#q-'+CSS.escape(b.dataset.jump))?.scrollIntoView({behavior:'smooth',block:'start'}));}
function resetExam(){state[examId]={answers:{},flags:new Set(),submitted:false};resetTimer(true);renderExam();}
function expandDrills(t){const out=[];let n=1;t.drills.forEach(d=>d.stems.forEach(stem=>out.push({n:n++,stem,options:d.options,answer:d.answer,exp:d.exp})));return out.slice(0,30);}
function renderTheory(){const t=window.THEORY_TOPICS.find(x=>x.id===theoryId);$('#theoryNav').innerHTML=window.THEORY_TOPICS.map(x=>`<button data-topic="${x.id}" class="${x.id===theoryId?'active':''}">${x.icon} ${esc(x.title)}</button>`).join('');$('#topicTitle').textContent=`${t.icon} ${t.title}`;$('#topicBadge').textContent=t.examLinks;$('#theoryContent').innerHTML=t.html;renderPractice(t);$$('[data-topic]').forEach(b=>b.onclick=()=>{theoryId=b.dataset.topic;renderTheory();});$$('.subtabs button').forEach(b=>b.onclick=()=>{const target=b.dataset.sub;$$('.subtabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.subpanel').forEach(p=>p.classList.toggle('active',p.id===target));});}
function renderPractice(t){const qs=expandDrills(t);const ps=state.practice[t.id]||(state.practice[t.id]={answers:{},checked:false});$('#practiceCount').textContent=`30 câu trắc nghiệm · ${Object.keys(ps.answers).length}/30 đã làm`;$('#practiceList').innerHTML=qs.map(q=>`<div class="practice-item"><p><b>Câu ${q.n}.</b> ${esc(q.stem)}</p>${q.options.map((o,i)=>{const L='ABCD'[i];return `<label><input type="radio" name="p_${t.id}_${q.n}" value="${L}" ${ps.answers[q.n]===L?'checked':''}> <b>${L}.</b> ${esc(o)}</label>`}).join('')}<div class="practice-exp ${ps.checked?'show':''}">${ps.checked?`<b>${ps.answers[q.n]===q.answer?'✓ Đúng':'Đáp án: '+q.answer}</b> — ${esc(q.exp)}`:''}</div></div>`).join('');$$(`#practiceList input[type=radio]`).forEach(i=>i.onchange=()=>{const n=i.name.split('_').pop();ps.answers[n]=i.value;updatePracticeBar(t);});$('#checkPractice').onclick=()=>{ps.checked=true;renderPractice(t);};$('#resetPractice').onclick=()=>{state.practice[t.id]={answers:{},checked:false};renderPractice(t);};updatePracticeBar(t);}
function updatePracticeBar(t){const qs=expandDrills(t),ps=state.practice[t.id];let correct=0;qs.forEach(q=>{if(ps.answers[q.n]===q.answer)correct++;});const done=Object.keys(ps.answers).length;$('#practiceCount').textContent=`30 câu trắc nghiệm · ${done}/30 đã làm${ps.checked?` · ${correct}/30 đúng`:''}`;$('#practiceFill').style.width=`${done/30*100}%`;}
function renderAnswerKey(){const ex=window.EXAMS[examId];$('#answerTestName').textContent=ex.title;$('#answerTableBody').innerHTML=ex.questions.map(q=>`<tr><td><b>${q.id}</b></td><td>${q.type==='mcq'?`<span class="pill p-green">${q.answer}</span>`:`<span class="pill p-yellow">Model</span>`}</td><td>${esc(q.type==='mcq'?q.options['ABCD'.indexOf(q.answer)]:(q.model||''))}</td><td>${esc(q.explainVi)}</td></tr>`).join('');}
function init(){initNav();$$('.test-card').forEach(c=>c.onclick=()=>{setExam(c.dataset.test);renderAnswerKey();});$('#resetExam').onclick=resetExam;$('#timerReset').onclick=()=>resetTimer(true);$('#answerTest1').onclick=()=>{examId='test1';renderAnswerKey();};$('#answerTest2').onclick=()=>{examId='test2';renderAnswerKey();};setExam('test1');resetTimer(true);renderTheory();renderAnswerKey();}
document.addEventListener('DOMContentLoaded',init);
})();
