const M=(id,section,stem,options,answer,explainVi,extra={})=>({id,section,type:'mcq',stem,options,answer,explainVi,...extra});
const T=(id,section,stem,model,explainVi,extra={})=>({id,section,type:extra.type||'text',stem,model,explainVi,...extra});
const P=(title,text)=>({title,text});

const teenPassage=P('Teenagers and Part-time Jobs',`More than 80% of American high school students do jobs in the evening on weekends or in summers. These jobs bring teenagers great advantages. One of the benefits of the work is the students can learn the skills that will be useful for the rest of their lives. When the students work, they have to manage both the job and schoolwork. To be able to do so, they must be very organized and able to keep a sensible schedule. They also learn to cope with the job stress apart from the stress of the schoolwork. Some of the most stressful jobs include teaching, nursing, and police work.

High school students who work are more likely to succeed as adults than people who enter the job market at a later age with no work experience. Teenagers want a lot of expensive things: clothes, mp3 players, smartphones, etc. Not all parents can afford them. And even if they can, the teens might not really appreciate that money because they did not earn it. When teenagers make money for themselves, they know its true value and are less likely to spend it foolishly.`);
const eduPassage=P('History of Education',`In the earliest times children got their education directly from parents and other adults. They learned main skills for survival. Adults passed down this knowledge through spoken language. Eventually cultures around the world began inventing writing. As societies developed, they set up schools to teach reading, writing, maths and other subjects. The first schools were usually just for boys. Most of the students came from rich and powerful families. Often the purpose of their education was religious training.

Many schools focused on military training. Sometimes youths attended special schools to learn the art of public speaking. These skills were meant to help them become future leaders. Most girls received their education at home. They learned cooking, sewing and other useful skills. Over time, education became available to more people, not just the rich and powerful. The governments of some countries set up public systems of education in the 1800s. During the 1900s, testing became a regular part of formal education.`);

const test1=[
M('1','S1','Which word has the underlined final -s pronounced differently from the others?',['ploughs','plays','likes','listens'],'C','Trong “likes”, -s theo sau /k/ (phụ âm vô thanh) nên đọc /s/. Các từ còn lại có -s đọc /z/.',{marks:1}),
M('2','S1','Which word has the underlined ending pronounced differently from the others?',['learned','needed','wanted','naked'],'A','“learned” (động từ quá khứ của learn) có -ed đọc /d/. “needed”, “wanted” có /ɪd/; “naked” là tính từ đặc biệt kết thúc bằng âm /ɪd/.',{marks:1}),
M('3','S1','Identify the word whose “ch” differs in pronunciation.',['change','chemist','chair','chicken'],'B','“chemist” có ch = /k/. Ba từ còn lại có ch = /tʃ/.',{marks:1}),
M('4','S1','My mother suggested that I _____ some outdoor activities.',['join','to join','joining','should join'],'D','Theo đáp án nguồn: D. Cấu trúc: suggest + that + S + (should) + V nguyên mẫu. Lưu ý đặc biệt: trong mandative subjunctive, “suggested that I join” cũng chuẩn ngữ pháp, nên A cũng có thể chấp nhận trong nhiều hệ thống tiếng Anh.',{marks:1}),
M('5','S1','This is the bike _____ my father bought two years ago.',['who','whom','whose','which'],'D','“bike” là vật nên dùng which. Which ở đây làm tân ngữ của bought; trong mệnh đề xác định còn có thể lược bỏ: “the bike my father bought…”.',{marks:1}),
M('6','S1','I was watching TV while my sister _____ to the music.',['was listening','listened','listens','were listening'],'A','Hai hành động đang diễn ra song song tại một thời điểm trong quá khứ → Past Continuous ở cả hai vế. Chủ ngữ “my sister” số ít → was listening.',{marks:1}),
M('7','S1','Children have to go to school _____ the summer.',['at','in','on','with'],'B','Dùng “in” với mùa: in summer / in the summer. “On” dùng với ngày; “at” thường dùng với thời điểm cụ thể.',{marks:1}),
M('8','S1','_____ it rained very hard, we put off our picnic.',['Because','Although','Because of','Despite'],'A','Sau chỗ trống là một mệnh đề “it rained…”, và quan hệ là nguyên nhân → Because + clause. Because of/Despite cần noun phrase hoặc V-ing.',{marks:1}),
M('9','S1','Our environment is heavily _____.',['pollution','polluted','pollute','pollutant'],'B','Sau “is heavily” cần tính từ/phân từ để mô tả trạng thái. “polluted” là past participle dùng như adjective.',{marks:1}),
M('10','S1','We went to school late because my alarm clock went _____.',['on','off','up','of'],'B','Cụm động từ “go off” dùng cho chuông/báo thức = reo, kêu.',{marks:1}),
M('11','S1','If you _____ in my position, you would behave the same.',['set','put','think','consider'],'B','Cụm cố định: put yourself/someone in someone’s position = đặt mình/ai vào hoàn cảnh của người khác. Câu đầy đủ tự nhiên hơn là “If you were put in my position…”.',{marks:1}),
M('12','S1','The facsimile _____ by Alexander Bain in 1843.',['invented','was invented','is invented','has been invented'],'B','Sự việc hoàn tất trong quá khứ + chủ ngữ nhận hành động → Past Simple Passive: was/were + V3.',{marks:1}),
M('13','S1','Too much exercise can be _____ but walking is good for your health.',['harmless','harmful','harmed','harming'],'B','Sau “be” cần adjective. “harmful” = có hại, phù hợp ý đối lập với “good for your health”.',{marks:1}),
M('14','S1','They still managed to _____ in touch after 20 years.',['take','have','make','keep'],'D','Collocation cố định: keep in touch = giữ liên lạc.',{marks:1}),
M('15','S1','Identify the mistake: Everyone (A) at the party (B) were (C) happy and laughed (D) a lot.',['A','B','C','D'],'C','Everyone là đại từ bất định số ít → phải dùng “was”, không dùng “were”.',{marks:1}),
M('16','S1','Identify the mistake: My mother (A) is interesting (B) in (C) reading books, especially novels (D).',['A','B','C','D'],'B','Người cảm thấy hứng thú → interested in. “Interesting” mô tả vật/sự việc gây hứng thú.',{marks:1}),
M('17','S1','Identify the mistake: It is (A) so (B) a difficult question (C) that no one can answer (D).',['A','B','C','D'],'B','Không dùng “so + a + adjective + noun” theo trật tự này. Đúng: “such a difficult question” hoặc “so difficult a question”.',{marks:1}),
M('18','S1','Identify the mistake: The little girl was (A) frightening (B) when she heard (C) the loud noise (D).',['A','B','C','D'],'B','Cô bé cảm thấy sợ → frightened. “Frightening” = gây sợ hãi.',{marks:1}),
M('19','S1','Identify the mistake: Physics (A) are (B) a difficult but (C) interesting subject (D).',['A','B','C','D'],'B','Tên môn học “Physics” dù kết thúc bằng -s vẫn được xem là danh từ số ít → Physics is…',{marks:1}),
M('20','S1','Identify the mistake: Mr. Brown, (A) that (B) teaches me English, (C) is coming today (D).',['A','B','C','D'],'B','Mệnh đề quan hệ không xác định (có dấu phẩy) không dùng “that”. Với người dùng “who”: Mr. Brown, who teaches me English, …',{marks:1}),
M('21A','S1','According to the passage, what is the best title?',['Advantages of jobs','Advantages and disadvantages of jobs','Disadvantages of part time jobs','Stress of schoolwork'],'A','Đoạn văn tập trung gần như hoàn toàn vào lợi ích của việc làm thêm đối với thanh thiếu niên: kỹ năng, tổ chức thời gian, kinh nghiệm và ý thức về tiền.',{marks:1,passage:teenPassage}),
M('21B','S1','What is NOT a benefit mentioned in the passage?',['Learning useful skills','Spending money foolishly','Coping with stress','Keeping a schedule'],'B','Bài đọc nói người đi làm “less likely to spend it foolishly”, tức ít tiêu tiền hoang phí hơn. Vì vậy “spending money foolishly” không phải lợi ích.',{marks:1,passage:teenPassage}),
M('21C','S1','Which jobs are specifically listed as stressful in the text?',['Farming and sales','Teaching and nursing','Engineering and law','Cooking and cleaning'],'B','Bài đọc nêu teaching, nursing và police work. Trong các lựa chọn, cặp khớp là Teaching and nursing.',{marks:1,passage:teenPassage}),
M('22A','S1','In the earliest times, children learned skills mainly for:',['Religious training','Military power','Survival','Public speaking'],'C','Câu đầu đoạn đọc nêu trẻ em học “main skills for survival”.',{marks:1,passage:eduPassage}),
M('22B','S1','Which of the following is NOT true according to the passage?',['Early schools were mainly for boys from rich families.','Knowledge was originally passed down through writing.','Public education systems emerged in the 1800s.','Testing became regular in the 1900s.'],'B','Thông tin ban đầu được truyền bằng spoken language, không phải writing. Ba lựa chọn còn lại đều được nêu trong passage.',{marks:1,passage:eduPassage}),
M('23','S1','Saint David is the patron saint of:',['England','Scotland','Wales','Ireland'],'C','Theo nguồn đáp án, Saint David là vị thánh bảo trợ của Wales.',{marks:1}),
M('24','S1','The Welsh national symbols mentioned in the text are:',['Roses and Lilies','Leeks and Daffodils','Potatoes and Thistles','Apples and Oak trees'],'B','Theo nguồn, leek và daffodil là các biểu tượng quốc gia của Wales, thường xuất hiện trong dịp Saint David’s Day.',{marks:1}),
M('25','S1','What is the capital city of Wales?',['London','Edinburgh','Cardiff','Belfast'],'C','Cardiff là thủ đô của Wales và được nguồn nhắc tới trong ngữ cảnh Saint David’s Day.',{marks:1}),
M('26','S1',"In the context of Sahara ecosystem, 'ecoregion' refers to:",['A political boundary','A specific area with distinct plants and animals','A type of weather forecast','A method of irrigation'],'B','Ecoregion là khu vực sinh thái có đặc điểm môi trường và hệ động/thực vật riêng biệt.',{marks:1}),
M('27','S1','Cacao trees can only be grown in:',['Cold countries','Hot countries','Underground','Desert areas'],'B','Nguồn nêu cây cacao cần khí hậu ấm/nóng nên được trồng ở các quốc gia nóng.',{marks:1}),
T('28','S2','Air pollution is a cause of _____ in human beings.','ill health','Nguồn đáp án nêu “ill health”. Đây là cụm danh từ nghĩa là tình trạng sức khỏe kém.',{marks:2,accepted:['ill health','illness'],keywords:['ill']}),
T('29','S2','The most important _____ on television recently has been technology.','influence','“Influence” là danh từ phù hợp sau “the most important” và khớp nguồn đáp án.',{marks:2,accepted:['influence'],keywords:['influence']}),
T('30','S2','The Internet is a very fast and convenient way to get _____.','information','Cụm tự nhiên “get information”; information là danh từ không đếm được.',{marks:2,accepted:['information'],keywords:['information']}),
T('31','S2','Leeks and _____ are Welsh national symbols.','daffodils','Nguồn Saint David’s Day nêu hai biểu tượng: leeks và daffodils.',{marks:2,accepted:['daffodils'],keywords:['daffodil']}),
T('32','S2','About twenty per cent of the present energy already comes from the _____ in one form or another.','sun','Theo nguồn, khoảng 20% năng lượng hiện tại đến từ mặt trời dưới dạng này hay dạng khác.',{marks:2,accepted:['sun'],keywords:['sun']}),
T('33','S2','Water is one of our most _____ resources.','precious','Cụm “precious resources” = nguồn tài nguyên quý giá.',{marks:2,accepted:['precious'],keywords:['precious']}),
T('34','S2','Children back then saw _____ as their playground and were curious to explore it.','nature','Nguồn “50 years back in time” mô tả nature như sân chơi của trẻ em.',{marks:2,accepted:['nature'],keywords:['nature']}),
T('35','S2',"The cloth made in Genoa was _____ and the pants were called 'jeans'.",'bleu (de Genes)','Nguồn đáp án liên hệ tên gọi với “bleu de Genes”. Chấp nhận các dạng nguồn ghi nhận như bleu/Genes.',{marks:2,accepted:['bleu','genes','blue'],keywords:['bleu']}),
T('36','S2','Knowledge of English is one of the most important _____ that help you use the Internet.','aspects','Theo nguồn đáp án, “aspects” là từ khóa được dùng để chỉ một yếu tố quan trọng giúp sử dụng Internet.',{marks:2,accepted:['aspects','factors'],keywords:['aspect']}),
T('37','S2','Most animals in the Sahara get their water through _____ processes.','metabolic','“Metabolic processes” = các quá trình trao đổi chất bên trong cơ thể giúp tạo/thu nước.',{marks:2,accepted:['metabolic'],keywords:['metabolic']}),
T('38','S3',"Rewrite: 'The red car is more expensive than the black car.' Start with 'The black car…'",'The black car is not as expensive as the red car.','Đổi so sánh hơn sang cấu trúc not as…as. Cũng có thể viết “The black car is cheaper than the red car.”',{marks:2,keywords:['black car','not as expensive','red car']}),
T('39','S3',"Reported Speech: 'What are you doing?' He asked me.",'He asked me what I was doing.','Câu hỏi Wh-: asked + object + wh-word + S + V; lùi thì are doing → was doing; không đảo trợ động từ trong câu gián tiếp.',{marks:2,keywords:['asked me','what','was doing']}),
T('40','S3',"Rewrite: 'The last time I saw her was five months ago.' Start with 'I…'",`I haven't seen her for five months.`,'Mẫu: The last time + past simple + was + duration ago → S + have/has not + V3 + for + duration.',{marks:2,keywords:["haven't seen",'five months']}),
T('41','S3',"Passive Voice: 'People built this pagoda many years ago.'",'This pagoda was built many years ago.','Đưa tân ngữ lên làm chủ ngữ; Past Simple Passive = was/were + V3.',{marks:2,keywords:['pagoda','was built','many years ago']}),
T('42','S3',"Rewrite: 'Magazines are not as informative as newspapers.' Start with 'Newspapers are…'",'Newspapers are more informative than magazines.','not as + adjective + as ↔ comparative adjective + than.',{marks:2,keywords:['newspapers','more informative','magazines']}),
T('43','S3',"Wish clause: 'I am sorry I do not know the way to your house.'",'I wish I knew the way to your house.','Ước trái với hiện tại: wish + past simple. know → knew.',{marks:2,keywords:['wish','knew','way']}),
T('44','S3',"Rewrite: 'Study hard or you will fail this exam.' Start with 'If you…'",`If you don't study hard, you will fail this exam.`,'“Imperative + or + result” có thể chuyển thành If + negative present simple, will + V.',{marks:2,keywords:['if',"don't study hard",'will fail']}),
T('45','S3',"Rewrite: 'They will not announce the findings until next week.' Start with 'No…'",'No announcement of the findings will be made until next week.','Chuyển động từ announce thành danh từ announcement và dùng bị động “will be made”.',{marks:2,keywords:['no announcement','findings','will be made','until next week']}),
T('46','S3','According to the education passage, why were the first schools usually just for boys?','The first schools were primarily for boys from rich and powerful families, often focusing on religious training or military skills to prepare them as future leaders.','Câu trả lời cần nêu hai ý: đối tượng ban đầu chủ yếu là con trai thuộc gia đình giàu/quyền lực và mục đích thường gắn với tôn giáo, quân sự hoặc đào tạo lãnh đạo.',{marks:2,passage:eduPassage,keywords:['boys','rich','powerful','religious']}),
T('47','S3',"Explain one advantage of studying English in Britain versus staying in one's own country.",'One major advantage is being surrounded by the language at all times, which forces you to speak and listen to English constantly and can lead to faster progress.','Ý chính theo nguồn: immersion – được bao quanh bởi tiếng Anh liên tục, buộc người học nghe/nói thường xuyên và tiến bộ nhanh hơn.',{marks:2,keywords:['surrounded','language','speak','listen']}),
T('48','S4',"Describe the environmental impact of air pollution as detailed in the 'Air Pollution' passage. Mention human health and potential climate changes.",'Air pollution is a major cause of ill health, specifically linked by doctors to lung diseases. Children in high-lead areas may suffer from cognitive delays and clumsiness. Environmentally, the increase in atmospheric gases contributes to global warming, which threatens to melt polar ice caps and lead to devastating floods.','Bài 3–5 câu nên có: (1) ill health/lung disease; (2) ảnh hưởng chì với trẻ em; (3) tăng khí trong khí quyển → global warming; (4) băng cực tan → nguy cơ lũ lụt.',{marks:5,type:'long',keywords:['ill health','lung','global warming','ice','flood']}),
T('49','S4',"Summarize the history and cultural significance of Saint David's Day in Wales.",`Saint David's Day is celebrated annually on March 1st and honors the patron saint of Wales, who died in 589. It is a significant national day when people wear symbols such as leeks and daffodils. Celebrations include national costumes, parades in Cardiff, poetry readings and community events.`,'Đáp án cần thể hiện: ngày 1/3; tưởng niệm Saint David – patron saint of Wales; biểu tượng leek/daffodil; các hoạt động văn hóa như trang phục, diễu hành ở Cardiff, đọc thơ và sinh hoạt cộng đồng.',{marks:5,type:'long',keywords:['March 1','patron saint','Wales','leeks','daffodils','Cardiff']}),
T('50','S4',"Explain the evolution of education from 'earliest times' to the 1900s.",'Education began with parents passing survival skills via spoken language. With the invention of writing, formal schools emerged but were initially restricted mainly to wealthy boys for religious or leadership training. Public education systems expanded in the 1800s, and by the 1900s formal testing had become a regular part of education.','Trình bày theo trình tự thời gian: gia đình truyền kỹ năng sinh tồn bằng lời nói → chữ viết và trường học → ban đầu chủ yếu con trai giàu có → hệ thống giáo dục công thế kỷ 19 → kiểm tra chính quy phổ biến ở thế kỷ 20.',{marks:5,type:'long',passage:eduPassage,keywords:['survival','spoken','schools','1800','1900','testing']}),
T('51','S4',"Discuss the debate regarding tourism's effect on traditional cultures according to the 'Travelling' passage.",`Tourism has dual effects on traditional culture. On the positive side, it can motivate locals to preserve music, food and history for visitors. On the negative side, critics argue that it may create 'fake' traditions performed mainly for money while everyday life becomes increasingly globalized.`,'Cần cân bằng hai mặt: du lịch tạo động lực giữ gìn văn hóa truyền thống, nhưng cũng có thể thương mại hóa văn hóa thành “màn trình diễn” thiếu tính chân thực.',{marks:5,type:'long',keywords:['preserve','music','food','fake','money','globalized']}),
T('52','S4','Based on the Sahara Desert text, explain how animals and plants have adapted to survive in such an extreme environment.','Plants can recover after severe leaf dehydration. Animals can survive major losses of body mass and many obtain water through internal metabolic processes rather than depending on scarce liquid water. These adaptations allow life to persist in extreme heat and dryness.','Nêu cả thực vật và động vật: khả năng phục hồi sau mất nước; chịu mất khối lượng cơ thể; tạo/thu nước qua trao đổi chất; liên hệ với môi trường khô hạn cực đoan.',{marks:5,type:'long',keywords:['plants','dehydration','animals','metabolic','water']}),
T('53','S4',"Compare the benefits of teenage employment with the stress it creates, based on the 'Part-time jobs' passage.",'Teenage jobs develop useful life skills such as organization, scheduling and financial appreciation, and they may improve later success. However, combining work and school creates stress, so students must learn to manage both responsibilities and cope with job pressure.','Cần so sánh hai mặt: lợi ích về kỹ năng/kinh nghiệm/giá trị đồng tiền và áp lực khi phải cân bằng công việc với học tập.',{marks:5,type:'long',passage:teenPassage,keywords:['skills','organization','money','stress','school']}),
];

const dress=P('Dressmaking Customs and Professional Benefits',`In many societies, it was customary for women to make dresses on their own because professional garments cost too much. Ordinary women had little choice but to make their own clothing at home, a job so time-consuming that they often only owned and used one dress at a time. A new dress was typically only made when the old one was completely worn out.

In contrast, those who could afford professional services enjoyed several advantages. Professional seamstresses offered a substantial number of designs and materials. They produced high-quality garments using precise measurements and could perform alterations to ensure an exact fit. Furthermore, professional dresses were durable and aligned with current fashion trends. These benefits included variety in design, precision, durability, and the ability to adapt to changing styles.`);
const beach=P('Beach Erosion: Human and Natural Factors',`Coastal beaches are eroding at an accelerated rate due to a combination of human and natural factors. Human activities, such as the construction of hydroelectric dams, significantly contribute to this issue. These dams prevent the natural flow of sand and soil in rivers from reaching the sea, causing beaches to shrink. Additionally, land development—building homes and structures directly on beaches—weakens the coastline and increases its vulnerability to environmental forces.

Natural causes also play a critical role. On coasts with steep underwater slopes, waves naturally increase in size as they approach the shore. The repetitive force of these large waves crashing against rocks leads to constant erosion. Furthermore, climate change poses a long-term threat. Rising water levels continue to reduce the size of sandy beaches, which could severely impact local residents and the coastal tourism industry.`);
const tape=P('Medical Tape and Bio-inspired Design',`Medical tape is essential for patient care, yet its strong adhesive can often cause skin injuries, particularly in infants and the elderly. Infants lack an epidermis (a thick outer layer), and the skin of older individuals becomes thinner and more fragile with age. When the tape is removed, the adhesive can tear this sensitive skin, leading to irritation or scarring for millions of patients annually.

To address this, researchers have looked to nature for solutions. Spider webs, for example, consist of threads that are only partially sticky, despite being strong and elastic. This principle of non-continuous adhesive surface area inspired new designs. Professor Jeffrey Karp and his team developed a modified tape by adding a slick silicone layer between the backing and the adhesive. Using lasers to cut grid lines into the silicone, they ensured that only specific areas of the adhesive would contact the skin, allowing for easy removal without injury.`);
const optimism=P('The Optimism Bias',`Research in neuroscience and social science suggests that most people possess an 'optimism bias'—a tendency to overestimate the likelihood of positive outcomes. In business, entrepreneurs often demonstrate this bias; despite the fact that only 20% of new businesses survive their first year, many individuals continue to start new ventures. Similarly, sports fans often hold optimistic expectations for their teams that are based on personal opinions rather than statistical evidence.

Neuroscientist Tali Sharot argues that this bias is a 'helpful illusion.' It serves as an antidote to mental health issues like depression and anxiety. By expecting more from life, individuals are motivated to work harder to achieve their goals. Ultimately, this bias allows people to lead more fulfilling and successful lives by maintaining a positive outlook even in the face of objective risks.`);

const test2=[
M('1A','S1','According to the passage, why did ordinary women in historical societies primarily make their own dresses?',['Professional seamstresses did not use durable materials.','They preferred homemade designs over professional ones.','The cost of professional dresses was prohibitively high.','It was a legal requirement for women to sew their own garments.'],'C','Passage nói professional garments “cost too much”, nên phụ nữ bình thường phải tự may tại nhà.',{marks:2,passage:dress}),
M('1B','S1','Which of the following is identified as a specific benefit of hiring a professional seamstress?',['They provided garments that were less expensive than homemade ones.','They offered a wider variety of colors and patterns.','They avoided using precise measurements to save time.','They only produced one dress per person to ensure quality.'],'B','Passage nhấn mạnh số lượng designs/materials lớn, tạo nhiều lựa chọn về mẫu mã và màu sắc.',{marks:2,passage:dress}),
M('2A','S1','How do hydroelectric dams contribute to the shrinking of beaches according to the text?',['They increase the frequency of ocean storms.','They cause a decrease in the size of ocean waves.','They block sand and soil from being transported to the sea.','They divert river water away from coastal communities.'],'C','Đập thủy điện ngăn cát và đất trong sông đi ra biển, làm bãi biển mất nguồn bồi đắp và thu hẹp.',{marks:2,passage:beach}),
M('2B','S1','What natural feature is associated with the growth of larger waves near the shore?',['Flat underwater plains','Steep underwater slopes','Low water levels caused by climate change','The presence of coral reefs'],'B','Passage nêu rõ steep underwater slopes khiến sóng tự nhiên tăng kích thước khi đến gần bờ.',{marks:2,passage:beach}),
M('3','S1','Why are elderly patients specifically at risk of skin damage from traditional medical tape?',['Their skin has a thicker epidermis that traps the adhesive.','The adhesive reacts chemically with their medication.','They have an allergic reaction to the silicone layer.','Their skin becomes thinner and weaker as they age.'],'D','Da người cao tuổi mỏng và yếu dần theo tuổi, nên keo mạnh dễ làm rách da khi tháo băng.',{marks:2,passage:tape}),
M('4','S1','According to Professor Chris Dawson, why are entrepreneurs considered examples of strong optimism bias?',['They are immune to mental health problems like anxiety.','They enter business despite the high failure rate of new startups.','They rely solely on statistical evidence to make decisions.','They usually have extensive experience in the business world.'],'B','Chỉ khoảng 20% doanh nghiệp sống qua năm đầu nhưng nhiều người vẫn khởi nghiệp; đây là biểu hiện đánh giá quá cao khả năng kết quả tích cực.',{marks:2,passage:optimism}),
M('5A','S1','In traditional societies, what typically triggered the creation of a new dress for a woman?',['The existing dress becoming completely worn out.','A drop in the cost of fabric.','A professional seamstress coming to town.','The change of seasons.'],'A','Passage: một chiếc váy mới thường chỉ được làm khi chiếc cũ đã hoàn toàn worn out.',{marks:2,passage:dress}),
M('5B','S1',"What does the term 'alter' refer to in the context of professional dressmaking?",['Increasing the cost of the garment.','Creating a brand new design from scratch.','Selling the dress to another person.','Making changes to ensure an exact fit.'],'D','“Alter” trong ngữ cảnh may mặc = chỉnh sửa quần áo để vừa chính xác với người mặc.',{marks:2,passage:dress}),
M('6A','S1','Which human activity is mentioned as weakening the coast and making it more vulnerable to natural phenomena?',['Coastal tourism activities','Land development for homes and buildings','Hydroelectric power consumption','The planting of new trees on the shore'],'B','Việc xây nhà/công trình trực tiếp trên bãi biển làm bờ biển yếu hơn và dễ bị tác động tự nhiên.',{marks:2,passage:beach}),
M('6B','S1','According to the text, what is a likely consequence of rising water levels?',['A decrease in the size of ocean waves.','An increase in the number of steep underwater slopes.','The creation of new sandy beaches.','A reduction in the size of existing sandy beaches.'],'D','Mực nước tăng khiến các bãi cát vốn đã thu hẹp tiếp tục nhỏ hơn.',{marks:2,passage:beach}),
M('7','S1',"What is the 'epidermis' as described in the passage?",['A chemical adhesive used in medical tape.','A laser-cut grid line used in silicone.','The thick outer layer of the human skin.','A type of medical injury caused by tape removal.'],'C','Passage định nghĩa trực tiếp epidermis là lớp ngoài dày của da/cơ thể người.',{marks:2,passage:tape}),
M('8','S1',"According to Tali Sharot, how does the optimism bias influence a person's behavior regarding their goals?",['It leads them to work harder to achieve them.','It makes them ignore their goals entirely.','It forces them to rely on others for success.','It causes them to give up easily.'],'A','Kỳ vọng nhiều hơn vào cuộc sống thúc đẩy con người làm việc chăm chỉ hơn để đạt mục tiêu.',{marks:2,passage:optimism}),
M('9','S1',"Why was the task of making dresses at home described as 'consuming'?",['Because it consumed a large amount of electricity.','Because it required frequent travel to see seamstresses.','Because it required a lot of time and effort.','Because the materials were very expensive.'],'C','“Time-consuming” nghĩa là tốn nhiều thời gian; ngữ cảnh cho thấy việc tự may quá tốn công nên đôi khi chỉ có một váy để dùng.',{marks:2,passage:dress}),
M('10','S1','What specific technology was used to modify the silicone layer in the new medical tape design?',['A laser','Manual scissors','3D printing','A digital scanner'],'A','Nhóm nghiên cứu dùng laser để cắt các grid lines vào lớp silicone.',{marks:2,passage:tape}),
M('11','S1','What percentage of businesses typically survive beyond their first year, according to the passage?',['10 per cent','20 per cent','80 per cent','50 per cent'],'B','Passage nêu trực tiếp only 20% of new businesses survive their first year.',{marks:2,passage:optimism}),
M('12','S1','In the new tape design, which layer is placed between the backing and the adhesive?',['A layer of paper','A layer of spider silk','A layer of silicone','A layer of cotton'],'C','Thiết kế mới thêm một lớp silicone trơn giữa backing và adhesive.',{marks:2,passage:tape}),
M('13','S1','What is the predicted impact of shrinking beaches on the economy?',['It will lead to cheaper land development.','It will improve the hydroelectric industry.','It will have no effect on residents.','It could radically impact the coastal tourism industry.'],'D','Bãi biển thu hẹp có thể ảnh hưởng nghiêm trọng tới ngành du lịch ven biển – nguồn thu phụ thuộc vào chính bãi biển.',{marks:2,passage:beach}),
M('14','S1','What property of spider webs inspired the idea for the new medical tape?',['The fact that spider webs are made of silicone.','The fact that spiders can easily walk on their webs.','The fact that the adhesive does not cover the entire surface area.','The fact that spider webs are invisible to the eye.'],'C','Chỉ một số sợi của mạng nhện dính; bề mặt keo không liên tục. Nhóm nghiên cứu áp dụng nguyên lý này để giảm vùng keo tiếp xúc da.',{marks:2,passage:tape}),
M('15','S1','According to the passage, how do football fans often form their expectations?',['By analyzing statistical evidence from previous seasons.','Based on personal opinions rather than actual evidence.','By following the advice of professional neuroscientists.','By ignoring the improvements of their own team.'],'B','Kỳ vọng của người hâm mộ thường dựa trên opinion hơn là actual/statistical evidence.',{marks:2,passage:optimism}),
M('16','S1','What did professional dressmakers know that ordinary women might not have been aware of?',['How to make their own garments at home.','Which fashions were trendy and which were not.','How to save money by using cheap materials.','The exact cost of professional clothing.'],'B','Professional dressmakers biết xu hướng nào đang fashionable/trendy, giúp khách hàng theo kịp thời trang.',{marks:2,passage:dress}),
T('17A','S2','List two reasons why ordinary women in the past typically only owned one dress at a time.','Professional dresses were too expensive, and making garments at home was extremely time-consuming.','Hai nguyên nhân phải bám passage: giá váy chuyên nghiệp quá cao; tự may tại nhà mất rất nhiều thời gian/công sức.',{marks:5,passage:dress,keywords:['expensive','time']}),
T('17B','S2','Identify three benefits professional seamstresses provided regarding the fit and quality of the garment.','They took precise measurements, altered garments to ensure an exact fit, and produced durable, high-quality dresses.','Ba ý cốt lõi theo nguồn: precise measurements; alterations/exact fit; durability/high quality.',{marks:5,passage:dress,keywords:['measure','alter','fit','durable']}),
T('18A','S2',"Explain how human 'land development' specifically impacts the stability of coastlines.",'Building homes and structures directly on beaches weakens the coast and makes it more vulnerable to natural phenomena such as storms.','Cần nối đúng chuỗi nguyên nhân: xây dựng trên bãi biển → làm yếu bờ → tăng tính dễ tổn thương trước tác động tự nhiên.',{marks:5,passage:beach,keywords:['build','weak','vulnerable']}),
T('18B','S2',"What role do 'steep underwater slopes' play in natural beach erosion?",'They cause waves to grow larger as they approach the shore; repeated crashing of these larger waves against rocks causes constant erosion.','Nêu cơ chế hai bước: dốc ngầm lớn làm sóng tăng kích thước → sóng lớn va đập lặp lại vào đá → xói mòn.',{marks:5,passage:beach,keywords:['waves','larger','rocks','erosion']}),
T('19','S2','Describe the physiological reasons why infants are particularly susceptible to skin injury from medical tape.','Infants lack a developed epidermis, the thick outer protective layer of skin, so their skin is thinner and easier for strong adhesive to tear.','Theo nguồn, infant thiếu epidermis – lớp ngoài bảo vệ dày – nên da nhạy cảm và dễ bị keo mạnh làm rách.',{marks:5,passage:tape,keywords:['epidermis','thin','adhesive']}),
T('20','S2',"According to Tali Sharot, how is optimism bias beneficial to an individual's mental health?",`It acts as an antidote to problems such as depression and anxiety, while positive expectations help people stay motivated and work toward a more fulfilling life.`,'Hai ý: optimism bias được xem như “helpful illusion/antidote” đối với depression/anxiety; đồng thời duy trì động lực và cảm giác cuộc sống tích cực.',{marks:5,passage:optimism,keywords:['depression','anxiety','motivat']}),
T('21','S3',"Compare and contrast the experiences of 'ordinary women' versus women who could 'afford dresses' in terms of ownership, variety, and production.",`Ordinary women often had to make their own clothes because professional dresses were too expensive. The work was so time-consuming that they might own only one dress at a time and replace it only when worn out. By contrast, wealthier women could choose from many designs and materials, receive precise measurements and alterations for an exact fit, and obtain durable dresses that followed current fashion trends.`,'Bài tốt phải so sánh theo ít nhất 3 trục: (1) chi phí/quyền sở hữu; (2) variety/design; (3) quy trình may – measurement/alteration/exact fit; có thể thêm durability/trends.',{marks:10,type:'long',passage:dress,keywords:['expensive','one dress','design','measure','alter','durable']}),
T('22','S3','Discuss the interplay between human activity and natural phenomena in coastal erosion. How do these factors combine to threaten tourism?',`Human factors such as hydroelectric dams reduce the sand and soil reaching the sea, while land development weakens the coastline. Natural factors include steep underwater slopes that produce larger waves and climate-change-driven rising water levels. Together, these forces shrink sandy beaches, damage coastal environments and threaten residents and the tourism industry that depends on attractive beaches.`,'Cấu trúc nên có: human factors (dams + development), natural factors (slopes/waves + rising water), rồi synthesis: bãi biển thu hẹp → tourism bị đe dọa.',{marks:10,type:'long',passage:beach,keywords:['dams','sand','development','slopes','water levels','tourism']}),
T('23','S3','Analyze how scientific research in medical technology and psychology seeks to improve human well-being using medical tape and optimism bias.',`Scientific research improves well-being in both physical and psychological ways. In medical technology, researchers copied the partly sticky structure of spider webs and added a laser-cut silicone layer so medical tape could be removed from sensitive skin with less injury. In psychology, research on optimism bias suggests that positive expectations can act as a helpful illusion, reducing the burden of depression and anxiety and motivating people to work harder toward goals. Both examples show how evidence-based understanding can be translated into better quality of life.`,'Cần tổng hợp hai lĩnh vực: medical tape = bio-inspired design giảm tổn thương thể chất; optimism bias = hiểu cơ chế tâm lý hỗ trợ sức khỏe tinh thần/động lực; cuối cùng nêu điểm chung: research → practical well-being.',{marks:10,type:'long',passage:{title:'Medical Tape + The Optimism Bias',text:tape.text+'\n\n'+optimism.text},keywords:['spider','silicone','injury','optimism','depression','anxiety','motivat']}),
];

window.EXAMS={
 test1:{id:'test1',title:'VLU Entrance Exam · Test 1',subtitle:'Đề 4 phần · nguồn đề PDF + đáp án Studocu do người dùng cung cấp',duration:120,sections:[['S1','Section 1 · Multiple Choice'],['S2','Section 2 · Fill in the Blanks'],['S3','Section 3 · Short Answer'],['S4','Section 4 · Long Answer']],questions:test1,sourceNote:'Đề: PDF VLU Test 1. Đáp án/Expected Answer: nội dung Studocu do người dùng cung cấp trực tiếp.'},
 test2:{id:'test2',title:'VLU Entrance Exam · Test 2',subtitle:'Đề 3 phần · PDF ngày 01.08.2026 + Markdown đáp án khớp cùng project Studocu',duration:90,sections:[['S1','Section 1 · Multiple Choice'],['S2','Section 2 · Short Answer'],['S3','Section 3 · Long Answer']],questions:test2,sourceNote:'Đề: van-lang-university-english-entrance-exam.pdf. Đáp án: Pasted markdown.md từ cùng project Studocu.'}
};
