const D=(stems,options,answer,exp)=>({stems,options,answer,exp});
const topic=(id,icon,title,examLinks,html,drills)=>({id,icon,title,examLinks,html,drills});
window.THEORY_TOPICS=[
topic('pronunciation','🔊','Pronunciation: -s/-es, -ed và “ch”','Test 1: Q1–Q3',`
<h5>1. Cách đọc -s / -es</h5><div class="formula">/s/ sau âm vô thanh /p, t, k, f, θ/ · /ɪz/ sau /s, z, ʃ, ʒ, tʃ, dʒ/ · /z/ trong các trường hợp còn lại.</div>
<p>Điểm quan trọng: nhìn <b>âm cuối</b>, không nhìn chữ cái cuối. Ví dụ <i>likes</i> /laɪks/ vì /k/ vô thanh → /s/; <i>plays</i> /pleɪz/ vì /eɪ/ là nguyên âm → /z/; <i>washes</i> /ˈwɒʃɪz/ vì /ʃ/ → /ɪz/.</p>
<div class="example"><b>Ví dụ:</b> books /s/ · bags /z/ · watches /ɪz/ · laughs /s/ · rooms /z/.</div>
<h5>2. Cách đọc -ed</h5><div class="formula">/t/ sau âm vô thanh (trừ /t/) · /d/ sau âm hữu thanh (trừ /d/) · /ɪd/ sau /t/ hoặc /d/.</div>
<p><i>worked</i> /t/; <i>played</i> /d/; <i>wanted</i>, <i>needed</i> /ɪd/. Không dựa vào chữ cuối, mà dựa vào âm cuối của động từ gốc.</p>
<div class="special"><b>Trường hợp đặc biệt:</b> một số tính từ có -ed phát âm /ɪd/ dù không theo quy tắc động từ, ví dụ <i>naked, wicked, beloved, sacred, learned</i> (khi <i>learned</i> là tính từ “uyên bác”). Nhưng <i>learned</i> là quá khứ của <i>learn</i> thường /lɜːnd/.</div>
<h5>3. “ch” không phải lúc nào cũng /tʃ/</h5><p>Phần lớn từ phổ thông: <i>chair, chicken, change</i> → /tʃ/. Nhiều từ gốc Hy Lạp: <i>chemist, chemistry, character, chorus, architect</i> → /k/. Một số từ gốc Pháp: <i>machine, chef, champagne</i> → /ʃ/.</p>
<div class="mistake"><b>Lỗi hay gặp:</b> đọc mọi “ch” thành /tʃ/ hoặc mọi -ed thành /ɪd/.</div>
<h5>Mẹo thi</h5><p>Đọc thành tiếng phần âm cuối của từ gốc trước, sau đó mới áp quy tắc. Với “ch”, học theo nhóm nguồn từ và ghi nhớ các ngoại lệ quen thuộc.</p>`,[
D(['Which word ends with /s/? — likes / plays / listens / ploughs','Which word ends with /s/? — books / rooms / bags / cars','Which word ends with /s/? — laughs / calls / stays / learns','Which word ends with /s/? — stops / comes / lives / sees','Which word ends with /s/? — cooks / reads / goes / runs'],['A','B','C','D'],'A','Âm cuối vô thanh /k, p, f…/ làm -s đọc /s/.'),
D(['Which word ends with /z/? — cats / maps / plays / laughs','Which word ends with /z/? — books / dogs / stops / cliffs','Which word ends with /z/? — cooks / rooms / hats / months','Which word ends with /z/? — writes / learns / laughs / stops','Which word ends with /z/? — bikes / bags / caps / roofs'],['A','B','C','D'],'C','Sau nguyên âm hoặc phụ âm hữu thanh, -s thường đọc /z/.'),
D(['Which word has -es pronounced /ɪz/? — watches / books / bags / cliffs','Which word has -es pronounced /ɪz/? — buses / cats / rooms / maps','Which word has -es pronounced /ɪz/? — washes / calls / stops / plays','Which word has -es pronounced /ɪz/? — changes / learns / cooks / laughs','Which word has -es pronounced /ɪz/? — roses / books / dogs / hats'],['A','B','C','D'],'A','Sau /s z ʃ ʒ tʃ dʒ/ ta thêm một âm tiết /ɪz/.'),
D(['Which -ed is /t/? — worked / played / needed / wanted','Which -ed is /t/? — laughed / called / invited / added','Which -ed is /t/? — washed / opened / decided / landed','Which -ed is /t/? — stopped / cleaned / wanted / needed','Which -ed is /t/? — watched / lived / started / ended'],['A','B','C','D'],'A','Sau âm vô thanh (không phải /t/), -ed đọc /t/.'),
D(['Which -ed is /ɪd/? — played / wanted / worked / called','Which -ed is /ɪd/? — needed / washed / cleaned / laughed','Which -ed is /ɪd/? — started / opened / lived / played','Which -ed is /ɪd/? — decided / watched / learned(verb) / called','Which -ed is /ɪd/? — added / worked / stopped / moved'],['A','B','C','D'],'A','Sau /t/ hoặc /d/, -ed đọc /ɪd/.'),
D(['Which “ch” is /k/? — chemist / chair / chicken / change','Which “ch” is /k/? — chemistry / child / choice / cheese','Which “ch” is /k/? — character / church / cheap / chat','Which “ch” is /k/? — chorus / chase / chapter / cherry','Which “ch” is /k/? — architect / chin / chop / chance'],['A','B','C','D'],'A','Nhiều từ gốc Hy Lạp có ch = /k/.')]),

topic('suggest','💡','Suggest, recommend và mandative subjunctive','Test 1: Q4',`
<h5>1. Hai cấu trúc quan trọng với suggest</h5><div class="formula">suggest + V-ing · suggest + that + S + (should) + V nguyên mẫu</div>
<p><b>Đúng:</b> She suggested <i>going</i> early. / She suggested that we <i>(should) go</i> early.</p><p><b>Sai:</b> suggest someone to do something trong nghĩa “đề nghị ai làm”.</p>
<div class="special"><b>Trường hợp đặc biệt:</b> Anh-Mỹ học thuật thường dùng <i>mandative subjunctive</i>: “I suggest that he <b>be</b> careful”, không chia <i>is</i>. Anh-Anh thường dùng <i>should + V</i>: “I suggest that he should be careful”. Cả hai đều chuẩn.</div>
<h5>2. Recommend / insist / demand / request</h5><p>Các động từ mang nghĩa yêu cầu/đề nghị có thể theo mẫu tương tự: <i>recommend that she apply</i>; <i>insist that he be present</i>; <i>demand that the report be revised</i>.</p>
<h5>3. Suggest còn có nghĩa “gợi cho thấy”</h5><p>Khi <i>suggest</i> = “cho thấy/ngụ ý”, không dùng mandative: <i>The evidence suggests that he <b>is</b> innocent.</i></p>
<div class="mistake"><b>Lỗi hay gặp:</b> “My mother suggested me to join…” → sửa thành “suggested that I join/should join…” hoặc “suggested joining…”.</div>`,[
D(['My teacher suggested that I ___ harder.','They suggested that he ___ earlier.','I suggest that she ___ the form today.','The doctor suggested that he ___ more rest.','We suggested that Tom ___ by bus.'],['study','studies','to study','studying'],'A','Sau suggest that + S dùng bare infinitive trong mandative subjunctive.'),
D(['She suggested ___ a taxi.','He suggested ___ at home.','They suggested ___ the meeting.','I suggested ___ earlier.','We suggested ___ the plan first.'],['to take','taking','take','took'],'B','suggest + V-ing khi không có mệnh đề that.'),
D(['Which is correct?','Choose the correct sentence.','Select the grammatical option.','Which sentence follows the rule?','Pick the best form.'],['She suggested me to go.','She suggested that I go.','She suggested I to go.','She suggested me going to.'],'B','Không dùng suggest + object + to-infinitive theo nghĩa đề nghị.'),
D(['The committee recommended that the rule ___ revised.','The doctor recommended that he ___ tested.','They demanded that the door ___ closed.','She insisted that the report ___ finished.','The manager requested that the form ___ signed.'],['is','be','was','being'],'B','Mandative subjunctive dùng be, kể cả bị động: be + V3.'),
D(['The evidence suggests that he ___ right.','The data suggests that sales ___ rising.','Her smile suggested that she ___ pleased.','The results suggest that the method ___ effective.','His tone suggested that he ___ angry.'],['is','be','being','to be'],'A','Suggest = indicate/imply không phải lời đề nghị, nên chia động từ bình thường.'),
D(['In British English, a common alternative is: “I suggest that he ___ leave now.”','Choose the British-style option: “They recommended that we ___ wait.”','Complete: “She insisted that he ___ apologize.”','Complete: “We requested that she ___ attend.”','Complete: “They proposed that the meeting ___ start at nine.”'],['should','to','would','can'],'A','Should + bare infinitive là mẫu rất phổ biến trong Anh-Anh.')]),

topic('relative','🧩','Relative clauses: who, whom, which, whose, that','Test 1: Q5, Q20',`
<h5>1. Chọn đại từ quan hệ theo chức năng</h5><div class="formula">who = người (chủ ngữ) · whom = người (tân ngữ, trang trọng) · which = vật · whose = sở hữu · that = người/vật trong mệnh đề xác định</div>
<p><i>The teacher who helped me…</i> · <i>The bike which I bought…</i> · <i>The student whose phone rang…</i></p>
<h5>2. Defining vs non-defining</h5><p><b>Defining</b>: thông tin cần thiết, không dấu phẩy, có thể dùng <i>that</i>. <b>Non-defining</b>: thông tin bổ sung, có dấu phẩy, <b>không dùng that</b>.</p>
<div class="special"><b>Lược bỏ:</b> Có thể bỏ who/whom/which/that khi nó làm <b>tân ngữ</b> trong defining clause: <i>The bike (which) I bought…</i>. Không bỏ khi làm chủ ngữ: <i>The man who lives next door…</i></div>
<h5>3. Giới từ + relative pronoun</h5><p>Trang trọng: <i>the person to whom I spoke</i>, <i>the company for which she works</i>. Không dùng <i>that</i> ngay sau giới từ.</p>
<h5>4. Which có thể thay cả mệnh đề</h5><p><i>He missed the bus, which made him late.</i> “which” ở đây chỉ toàn bộ sự việc phía trước.</p>`,[
D(['The woman ___ teaches us is from Hue.','The man ___ called you is outside.','Students ___ work hard usually improve.','The doctor ___ treated me was kind.','The boy ___ won the prize is my cousin.'],['who','whom','which','whose'],'A','Người + chức năng chủ ngữ → who.'),
D(['The book ___ I bought is useful.','The car ___ she drives is new.','The phone ___ he lost was expensive.','The movie ___ we watched was long.','The bag ___ you found is mine.'],['who','whom','which','whose'],'C','Vật → which; vì là tân ngữ nên defining clause còn có thể lược which.'),
D(['The student ___ laptop broke left early.','The woman ___ son is a pilot lives here.','The company ___ office moved is hiring.','The teacher ___ class won smiled.','The dog ___ tail is white is friendly.'],['who','whom','which','whose'],'D','Sở hữu → whose + noun.'),
D(['Mr Lee, ___ teaches chemistry, is absent.','My aunt, ___ lives in Da Nang, is visiting.','Tom, ___ works nearby, called me.','Ms Hoa, ___ helped us, is retiring.','Nam, ___ won the contest, thanked everyone.'],['that','who','which','whose'],'B','Non-defining clause với người dùng who; không dùng that.'),
D(['The person to ___ I spoke was helpful.','The client with ___ we met agreed.','The teacher from ___ I learned retired.','The manager for ___ she works is abroad.','The colleague about ___ they complained resigned.'],['who','whom','that','which'],'B','Sau giới từ và chỉ người → whom trong văn phong trang trọng.'),
D(['He forgot the key, ___ made us wait.','The train was cancelled, ___ caused delays.','She passed the exam, ___ surprised everyone.','They moved away, ___ saddened us.','It rained all day, ___ ruined the picnic.'],['that','who','which','whose'],'C','Which có thể thay cho cả mệnh đề trước trong non-defining clause.')]),

topic('tenses','⏳','Past Continuous, while/when và timeline','Test 1: Q6',`
<h5>1. Past Continuous</h5><div class="formula">S + was/were + V-ing</div><p>Dùng cho hành động đang diễn ra tại một thời điểm trong quá khứ, bối cảnh, hoặc hai hành động song song.</p>
<div class="example">At 8 p.m., I <b>was studying</b>. · While I <b>was studying</b>, my sister <b>was listening</b> to music.</div>
<h5>2. While vs when</h5><p><b>while</b> thường đi với hành động kéo dài; <b>when</b> thường giới thiệu hành động ngắn xen vào: <i>I was sleeping when the phone rang.</i></p>
<div class="special"><b>Không máy móc:</b> “when” cũng có thể đi với Past Continuous nếu nghĩa yêu cầu: <i>When I was living in Hanoi, I met many artists.</i></div>
<h5>3. Stative verbs</h5><p>Know, believe, understand, love, want… thường không dùng continuous trong nghĩa trạng thái.</p>
<h5>4. Phối hợp thì</h5><p>Hai hành động đồng thời: was/were V-ing + while + was/were V-ing. Hành động nền + sự kiện chen vào: was/were V-ing + when + Past Simple.</p>`,[
D(['At 9 last night, I ___ TV.','At noon yesterday, she ___ lunch.','At 7 a.m. yesterday, they ___ to school.','At this time last Sunday, we ___ on the beach.','At 10 p.m., he ___ for the test.'],['was watching','watched','watches','has watched'],'A','Mốc thời gian cụ thể trong quá khứ + hành động đang diễn ra → Past Continuous.'),
D(['While I was reading, my sister ___.','While he was cooking, I ___.','While they were studying, we ___.','While Lan was working, Nam ___.','While she was talking, he ___.'],['was sleeping','slept suddenly','has slept','sleeps'],'A','Hai hành động kéo dài đồng thời → Past Continuous.'),
D(['I was walking home when it ___.','She was sleeping when the phone ___.','They were playing when it ___.','We were eating when he ___.','He was driving when the accident ___.'],['rained','was raining continuously','has rained','rains'],'A','Sự kiện ngắn xen vào hành động nền → Past Simple.'),
D(['Choose the best: While I ___, she called.','Complete: While he ___, the lights went out.','Complete: While we ___, it started raining.','Complete: While they ___, the teacher arrived.','Complete: While Mai ___, her friend texted.'],['was studying','studied yesterday','has studied','studies'],'A','Sau while, hành động đang diễn ra thường dùng Past Continuous.'),
D(['Which is normally NOT continuous?','Choose the stative verb.','Which verb usually describes a state?','Which verb is least likely in -ing here?','Select the stative verb.'],['know','run','write','cook'],'A','Know là stative verb trong nghĩa “biết”.'),
D(['My sister ___ to music while I was watching TV.','They ___ while we were talking.','He ___ while she was cooking.','I ___ while my brother was studying.','We ___ while the children were playing.'],['was listening','listened every day','has listened','listens'],'A','Hai hành động song song trong quá khứ → was/were + V-ing.')]),

topic('connectors','🧭','Prepositions of time + reason/concession','Test 1: Q7–Q8',`
<h5>1. in / on / at</h5><div class="formula">in + months/years/seasons/parts of day · on + days/dates · at + clock times/specific points</div><p><i>in summer, in 2026, in the morning</i> · <i>on Monday, on 16 August</i> · <i>at 7:30, at noon, at night</i>.</p>
<div class="special"><b>Không giới từ</b> trước last/next/this/every: <i>last Monday</i>, không phải <i>on last Monday</i>.</div>
<h5>2. Because vs because of</h5><div class="formula">because + S + V · because of + noun / noun phrase / V-ing</div>
<h5>3. Although / though / even though vs despite / in spite of</h5><div class="formula">although + clause · despite/in spite of + noun/V-ing · despite the fact that + clause</div>
<div class="mistake">Sai: “Despite it rained…” → đúng: “Although it rained…” hoặc “Despite the rain…”.</div>`,[
D(['We travel a lot ___ summer.','The course starts ___ September.','He was born ___ 2001.','Flowers bloom ___ spring.','I study best ___ the morning.'],['in','on','at','with'],'A','Mùa, tháng, năm, phần của ngày → in.'),
D(['The exam is ___ Monday.','We met ___ 16 August.','She works ___ Fridays.','The event is ___ New Year’s Day.','I arrived ___ Tuesday morning.'],['in','on','at','from'],'B','Ngày và ngày cụ thể → on.'),
D(['Meet me ___ 7:30.','The shop closes ___ noon.','I woke up ___ midnight.','We arrived ___ night.','Class starts ___ 8 o’clock.'],['in','on','at','by'],'C','Giờ/điểm thời gian cụ thể → at.'),
D(['We stayed home ___ it was raining.','She left early ___ she felt sick.','I called him ___ I needed help.','They cancelled the trip ___ the storm was severe.','He was late ___ his bus broke down.'],['because','because of','despite','although'],'A','Because + clause (S + V).'),
D(['We stayed home ___ the rain.','She missed class ___ illness.','The game stopped ___ heavy rain.','They were delayed ___ traffic.','He succeeded ___ many difficulties.'],['because','because of','although','so'],'B','Because of + noun phrase.'),
D(['___ it rained, we went out.','___ she was tired, she finished.','___ the task was hard, he continued.','___ they were poor, they were generous.','___ he apologized, she was still upset.'],['Although','Because of','Despite','Due to'],'A','Although + clause diễn tả nhượng bộ.')]),

topic('wordform','🎨','Word forms và -ed/-ing adjectives','Test 1: Q9, Q13, Q16, Q18',`
<h5>1. Xác định loại từ bằng vị trí</h5><p>Sau <b>be/seem/become</b> thường cần adjective; sau adjective + noun; sau động từ thường cần adverb để bổ nghĩa cách thức; sau mạo từ có thể cần noun.</p>
<div class="example">pollution (n) · pollute (v) · polluted/polluting (adj) · pollutant (n/adj).</div>
<h5>2. -ed vs -ing adjectives</h5><div class="formula">-ed = người/vật nhận cảm xúc · -ing = tác nhân gây cảm xúc</div><p><i>I am interested.</i> The book is <i>interesting.</i> · She was <i>frightened</i> by a <i>frightening</i> noise.</p>
<div class="special">Một số danh từ vô tri vẫn dùng -ed nếu diễn tả trạng thái bị tác động: <i>a damaged car, a polluted river</i>.</div>
<h5>3. Suffix thường gặp</h5><p>Noun: -tion, -ment, -ness, -ity · Adjective: -ful, -less, -ous, -ive, -al · Adverb: -ly.</p>`,[
D(['Our environment is heavily ___.','The river is badly ___.','The air became seriously ___.','The beach is heavily ___.','The area remains badly ___.'],['pollution','polluted','pollute','pollutant'],'B','Sau be/become/remain cần adjective; polluted mô tả trạng thái bị ô nhiễm.'),
D(['Too much exercise can be ___.','Smoking is ___ to health.','This chemical is ___ to fish.','The effect may be ___.','The substance is highly ___.'],['harm','harmful','harmed','harming'],'B','Cần adjective: harmful.'),
D(['I am ___ in science.','She is ___ in novels.','They are ___ in joining.','He became ___ in art.','We are ___ in the course.'],['interesting','interested','interest','interestingly'],'B','Người có cảm xúc → interested.'),
D(['The movie was very ___.','The lecture was ___.','The story is ___.','The game was ___.','The lesson became ___.'],['interested','interesting','interest','interestingly'],'B','Sự vật gây cảm xúc → interesting.'),
D(['She felt ___ by the noise.','The child was ___ by the dog.','We were ___ by the sudden bang.','He looked ___ after the accident.','They became ___ during the storm.'],['frightening','frightened','frighten','frighteningly'],'B','Người trải nghiệm cảm xúc → frightened.'),
D(['Choose the noun form of “pollute”.','Choose the noun form of “develop”.','Choose the noun form of “decide”.','Choose the noun form of “improve”.','Choose the noun form of “educate”.'],['pollution / development / decision / improvement / education','polluted','polluting','pollutant only'],'A','Danh từ thường được tạo bằng các hậu tố -tion/-ment/-ion.')]),

topic('collocations','🧲','Phrasal verbs và collocations','Test 1: Q10, Q11, Q14',`
<h5>1. Học theo cụm, không học từng từ rời</h5><p><b>go off</b> = chuông reo/nổ; <b>keep in touch</b> = giữ liên lạc; <b>put yourself in someone’s position</b> = đặt mình vào hoàn cảnh người khác.</p>
<h5>2. Phrasal verb đổi nghĩa mạnh</h5><p>go on = tiếp tục; go off = reo/hỏng; go out = ra ngoài/tắt; go up = tăng. Một giới từ/particle làm nghĩa đổi hoàn toàn.</p>
<h5>3. Collocation cố định</h5><p>make a decision, do homework, take responsibility, have difficulty, keep a promise, pay attention.</p>
<div class="special"><b>Mẹo:</b> nếu 4 lựa chọn đều “đúng nghĩa từ điển”, hãy kiểm tra cụm nào người bản ngữ dùng tự nhiên.</div>`,[
D(['My alarm clock went ___.','The fire alarm went ___.','The bell went ___ at 6.','The timer went ___.','The school alarm went ___.'],['on','off','up','of'],'B','go off = chuông/báo thức reo.'),
D(['We still ___ in touch.','Please ___ in touch.','They managed to ___ in touch.','Let’s ___ in touch.','I hope we can ___ in touch.'],['make','keep','do','take'],'B','Collocation cố định: keep in touch.'),
D(['Try to ___ yourself in my position.','Can you ___ yourself in her shoes?','___ yourself in his place.','Please ___ yourself in their situation.','If you ___ yourself in my position…'],['put','set','make','do'],'A','put yourself in someone’s position/shoes/place.'),
D(['Please ___ attention.','Students should ___ attention.','You need to ___ attention.','Always ___ attention to signs.','Try to ___ attention in class.'],['pay','make','do','keep'],'A','pay attention là collocation cố định.'),
D(['She ___ a decision.','They ___ an important decision.','We must ___ a decision.','He finally ___ his decision.','Can you ___ a decision now?'],['made','did','took','kept'],'A','make a decision.'),
D(['You should ___ responsibility.','He refused to ___ responsibility.','They must ___ responsibility.','Managers ___ responsibility for results.','She agreed to ___ responsibility.'],['take','make','do','keep'],'A','take responsibility for something.')]),

topic('passive','🏗️','Passive voice + subject–verb agreement','Test 1: Q12, Q15, Q19, Q41',`
<h5>1. Công thức bị động</h5><div class="formula">Active: S + V + O → Passive: O + be (đúng thì) + V3 (+ by S)</div><p>Past Simple: was/were + V3 · Present Simple: am/is/are + V3 · Present Perfect: has/have been + V3 · Future: will be + V3.</p>
<h5>2. Khi nào bỏ “by + agent”</h5><p>Bỏ khi tác nhân không quan trọng/không biết/hiển nhiên: <i>English is spoken worldwide.</i></p>
<h5>3. Subject–verb agreement</h5><p>Everyone/everybody/each/every + singular verb. Tên môn học kết thúc -s như <i>Physics, Mathematics, Economics</i> thường dùng singular khi nói về môn học.</p>
<div class="special"><b>Danh từ đặc biệt:</b> news is; police are; people are; trousers are; the United States is.</div>`,[
D(['The facsimile ___ in 1843.','This bridge ___ in 1990.','The school ___ last year.','The pagoda ___ long ago.','The road ___ in 2010.'],['invented','was built / was invented','is build','has build'],'B','Past Simple Passive = was/were + V3.'),
D(['English ___ worldwide.','Rice ___ in many countries.','Coffee ___ here.','Cars ___ in this factory.','The room ___ every day.'],['is/are + V3 as appropriate','was always','has + V1','do + V3'],'A','Present Simple Passive = am/is/are + V3.'),
D(['The report ___ by Friday.','The results ___ next week.','The bridge ___ next year.','The winner ___ tomorrow.','The plan ___ soon.'],['will be completed/announced/built','will completed','is completing','has complete'],'A','Future Passive = will be + V3.'),
D(['Everyone ___ happy.','Everybody ___ ready.','Each student ___ a card.','Every child ___ a seat.','Someone ___ outside.'],['is/has','are/have','were/have','be/have'],'A','Đại từ bất định everyone/everybody/each/someone dùng động từ số ít.'),
D(['Physics ___ interesting.','Mathematics ___ difficult.','Economics ___ useful.','Linguistics ___ fascinating.','Statistics ___ my favorite subject.'],['is','are','were','have'],'A','Tên môn học kết thúc -s thường được xem là số ít.'),
D(['The police ___ investigating.','People ___ waiting.','The trousers ___ new.','The news ___ surprising.','The United States ___ large.'],['are / are / are / is / is','is / is / is / are / are','are / is / are / are / is','is / are / is / is / are'],'A','Các danh từ đặc biệt có quy tắc agreement riêng; đáp án A liệt kê đúng thứ tự.')]),

topic('sosuch','⚖️','So / such và kỹ năng Error Identification','Test 1: Q17 + nhóm tìm lỗi',`
<h5>1. So và such</h5><div class="formula">so + adjective/adverb · so + adj + a/an + singular noun · such + (a/an) + adjective + noun</div>
<p><i>so difficult</i> · <i>so difficult a question</i> · <i>such a difficult question</i> · <i>such difficult questions</i>.</p>
<h5>2. so…that / such…that</h5><p><i>It was so cold that we stayed home.</i> · <i>It was such a cold day that we stayed home.</i></p>
<h5>3. Chiến lược tìm lỗi</h5><p>Quét theo thứ tự: subject–verb agreement → tense → word form → preposition/collocation → clause/relative pronoun → determiner/article → comparison.</p>
<div class="mistake">Sai: <i>so a difficult question</i>. Đúng: <i>such a difficult question</i> / <i>so difficult a question</i>.</div>`,[
D(['It is ___ difficult.','The test was ___ hard.','She spoke ___ quickly.','The bag is ___ heavy.','The film was ___ boring.'],['so','such','such a','so a'],'A','so + adjective/adverb.'),
D(['It is ___ difficult question.','That was ___ strange story.','She is ___ talented student.','It was ___ long journey.','He made ___ serious mistake.'],['so a','such a','such','so'],'B','such a + adjective + singular countable noun.'),
D(['It was ___ cold that we stayed home.','She was ___ tired that she slept early.','The task was ___ hard that he quit.','He ran ___ fast that nobody caught him.','The room was ___ noisy that I left.'],['so','such','such a','so a'],'A','so + adj/adv + that.'),
D(['It was ___ cold day that we stayed home.','She told ___ funny story that we laughed.','It was ___ difficult test that many failed.','They had ___ busy week that they rested Sunday.','He is ___ good teacher that students love him.'],['so','such a','so a','such'],'B','such a + adjective + singular noun + that.'),
D(['Find the error: Everyone were ready.','Find the error: Physics are difficult.','Find the error: She is interesting in art.','Find the error: Mr Lee, that teaches us, is kind.','Find the error: It is so a hard task.'],['verb/word after subject','article only','punctuation','none'],'A','Các câu đều có lỗi cốt lõi ở thành phần ngữ pháp chính (agreement/word form/relative/so-such).'),
D(['Best correction: “so a difficult question”','Best correction: “so a long journey”','Best correction: “so an interesting book”','Best correction: “so a strange idea”','Best correction: “so a serious problem”'],['such a/an + adjective + noun','so + noun only','very a + noun','such + adjective only'],'A','Đổi sang such a/an + adjective + noun là cách phổ biến nhất.')]),

topic('transform','✍️','Sentence Transformation: comparison, reported speech, perfect, wish, conditional, not until','Test 1: Q38–Q45',`
<h5>1. Comparison</h5><div class="formula">A is more adj than B ↔ B is not as adj as A</div><p><i>The red car is more expensive than the black car.</i> ↔ <i>The black car is not as expensive as the red car.</i></p>
<h5>2. Reported questions</h5><div class="formula">asked + object + wh-word + S + V (không đảo) · lùi thì khi cần</div><p>“What are you doing?” → He asked me what I was doing.</p>
<h5>3. The last time… ago</h5><div class="formula">The last time S + V2 was X ago ↔ S + have/has not + V3 + for X</div>
<h5>4. Wish hiện tại</h5><div class="formula">wish + Past Simple · be → were (trang trọng cho mọi ngôi)</div>
<h5>5. Imperative + or</h5><div class="formula">Do X or Y will happen ↔ If you do not do X, Y will happen</div>
<h5>6. Not until</h5><p>Có thể đổi sang danh hóa/bị động: <i>No announcement … will be made until…</i>. Nếu đưa <i>Not until</i> lên đầu câu, cần đảo trợ động từ: <i>Not until next week will they announce…</i></p>`,[
D(['A is taller than B → B is ___.','This book is more useful than that one → That one is ___.','Cars are faster than bikes → Bikes are ___.','Math is harder than art → Art is ___.','Today is hotter than yesterday → Yesterday was ___.'],['not as + adjective + as A','more adjective than A','the most adjective','as more adjective'],'A','So sánh hơn ↔ not as…as.'),
D(['“What are you doing?” → He asked me ___.','“Where do you live?” → She asked him ___.','“Why are they late?” → I asked ___.','“When will he come?” → She asked me ___.','“How did you know?” → He asked her ___.'],['wh-word + subject + verb (statement order)','auxiliary + subject + verb','to + verb only','if + inversion'],'A','Reported Wh-question giữ từ hỏi nhưng dùng trật tự câu trần thuật.'),
D(['The last time I saw her was five months ago.','The last time he visited was two years ago.','The last time we met was a month ago.','The last time she called was three weeks ago.','The last time they travelled was a year ago.'],['Use have/has not + V3 + for + duration','Use Past Continuous','Use will not + V','Use used to only'],'A','Mẫu present perfect negative + for.'),
D(['I am sorry I do not know → I wish I ___.','I am sorry I cannot swim → I wish I ___.','I regret that I am not taller → I wish I ___.','I am sorry she is not here → I wish she ___.','I regret I have no time → I wish I ___ more time.'],['past form / could as appropriate','present simple','will always','to-infinitive'],'A','Ước trái hiện tại dùng lùi về past form; can → could.'),
D(['Study hard or you will fail.','Hurry or you will miss the bus.','Wear a coat or you will be cold.','Leave now or you will be late.','Save money or you cannot buy it.'],['If + negative present, result with will/can','If + past perfect only','Although + clause','Because of + noun'],'A','Imperative + or → điều kiện loại 1 với mệnh đề if phủ định.'),
D(['They will not announce it until Friday.','She will not leave until noon.','We will not know until tomorrow.','He will not decide until next week.','They will not publish until Monday.'],['Not until + time + auxiliary + S + V','Not until + S + V without inversion','Until not + clause','No until + verb'],'A','Khi Not until đứng đầu, mệnh đề chính đảo trợ động từ.')]),

topic('readingmcq','📖','Reading MCQ: main idea, detail, NOT TRUE, vocab, cause–effect','Test 1: Q21–Q27 · Test 2: Section 1',`
<h5>1. Main idea / best title</h5><p>Tìm ý lặp lại xuyên đoạn, không chọn chi tiết chỉ xuất hiện một lần. Title tốt phải đủ rộng bao trùm nhưng không quá chung.</p>
<h5>2. Detail questions</h5><p>Gạch keyword trong câu hỏi, scan passage tìm paraphrase. Đáp án thường diễn đạt lại, không chép nguyên văn.</p>
<h5>3. NOT TRUE / NOT mentioned</h5><div class="formula">Ba lựa chọn phải được passage hỗ trợ; một lựa chọn trái hoặc không xuất hiện.</div><p>Đặc biệt chú ý từ phủ định NOT/EXCEPT.</p>
<h5>4. Vocabulary in context</h5><p>Dựa câu trước/sau, quan hệ cause-effect, contrast, example; không chọn nghĩa từ điển nếu không phù hợp văn cảnh.</p>
<h5>5. Cause–effect</h5><p>Tìm tín hiệu because, therefore, lead to, result in, cause, due to, as a result.</p>
<div class="special"><b>Quy tắc vàng:</b> đáp án phải được text hỗ trợ. Kiến thức ngoài bài dù đúng vẫn có thể là đáp án sai.</div>`,[
D(['For a “best title” question, prioritize…','For a “main idea” question, look for…','A good title should…','When two titles seem possible, choose…','The best summary usually…'],['the repeated central idea','the smallest detail','your outside knowledge','the longest option'],'A','Main idea/title phải bao quát ý trung tâm lặp lại.'),
D(['For a detail question, first…','To locate a fact quickly…','When a question names “hydroelectric dams”…','For a percentage question…','For a named person question…'],['scan for keywords/paraphrases','read only the title','guess from memory','choose the longest option'],'A','Scan keyword và paraphrase để định vị thông tin.'),
D(['In a NOT TRUE question, you should…','For EXCEPT questions…','When the stem says NOT mentioned…','For “Which is NOT a benefit?”…','For a negative-detail item…'],['verify the other three are supported','ignore NOT','choose a true statement','use outside knowledge'],'A','Câu phủ định cần kiểm tra kỹ ba lựa chọn được hỗ trợ và tìm ngoại lệ.'),
D(['For vocabulary in context, use…','To infer “alter” in dressmaking…','To infer “consuming”…','To understand “epidermis”…','To infer “ecoregion”…'],['nearby context and examples','only first dictionary meaning','word length','option position'],'A','Nghĩa trong văn cảnh dựa vào câu xung quanh và chức năng trong passage.'),
D(['“Dams block sand, causing beaches to shrink” is…','“Rising water reduces beaches” is…','“Thin skin leads to injury” is…','“Optimism makes people work harder” is…','“Work experience increases later success” is…'],['cause–effect','comparison only','definition only','chronology only'],'A','Các câu đều thể hiện quan hệ nguyên nhân–kết quả.'),
D(['If an option is scientifically true but not in the passage…','If your memory conflicts with the text…','If a detail seems plausible but unsupported…','If an option adds a new cause not mentioned…','If an answer exaggerates “may” into “always”…'],['do not select it unless text supports it','always choose it','prefer outside knowledge','ignore the wording'],'A','Reading comprehension chấm theo text, không theo kiến thức ngoài bài.')]),

topic('cloze','🧠','Contextual Fill-in-the-Blank & Vocabulary','Test 1: Section 2',`
<h5>1. Quy trình 4 bước</h5><p>(1) Xác định loại từ cần điền; (2) đọc collocation bên trái/phải; (3) dùng chủ đề/ngữ nghĩa; (4) kiểm tra số ít/số nhiều và chính tả.</p>
<h5>2. Collocation quan trọng trong nguồn</h5><p><i>ill health, get information, precious resources, national symbols, metabolic processes</i>.</p>
<h5>3. Dùng ngữ pháp để thu hẹp</h5><p>“one of the most ___ resources” → adjective; “comes from the ___” → noun; “through ___ processes” → adjective.</p>
<div class="special"><b>Instruction “ONE word”:</b> nếu nguồn key dùng cụm hai từ như “ill health”, cần ưu tiên quy định của đề; trong website sẽ hiển thị cả đáp án nguồn và ghi chú nếu wording nguồn có xung đột.</div>
<h5>4. Không điền từ chỉ vì nghĩa gần đúng</h5><p>Phải khớp collocation và câu gốc. Ví dụ “valuable resources” có nghĩa gần nhưng nguồn dùng <i>precious resources</i>.</p>`,[
D(['“get ___” in an Internet context','“obtain ___” from a website','“find ___ online”','“access ___ quickly”','“search for ___”'],['information','inform','informative','informed'],'A','Sau get/obtain/find/access cần noun “information”.'),
D(['“___ resources” meaning very valuable','“one of our most ___ resources”','“protect this ___ resource”','“water is a ___ resource”','“a highly ___ resource”'],['precious','preciously','preciousness','price'],'A','Cần adjective “precious”.'),
D(['“___ processes” related to body chemistry','Animals use ___ processes.','Water is produced by ___ processes.','Internal ___ processes help survival.','Through ___ processes…'],['metabolic','metabolism','metabolically only','metabolize'],'A','Adjective trước noun processes → metabolic.'),
D(['Leeks and ___ are Welsh symbols.','The flower paired with leeks is ___.','A Welsh national flower is the ___.','Saint David’s Day features leeks and ___.','The source pairs leek with ___.'],['daffodils','roses','thistles','lilies'],'A','Nguồn dùng daffodils.'),
D(['Energy comes from the ___.','Solar energy comes from the ___.','Twenty per cent comes from the ___.','The source of solar power is the ___.','Present energy partly comes from the ___.'],['sun','moon','soil','wind only'],'A','Nguồn nêu “the sun”.'),
D(['Children saw ___ as their playground.','They explored ___ outdoors.','The source describes ___ as a playground.','Children were curious to explore ___.','Back then, ___ was their playground.'],['nature','technology','school','television'],'A','Nguồn dùng “nature”.')]),

topic('written','📝','Short Answer & Long Answer: cách trả lời theo nguồn','Test 1: Sections 3–4 · Test 2: Sections 2–3',`
<h5>1. Short Answer</h5><p>Trả lời trực tiếp 1–3 câu, dùng đúng keyword từ passage nhưng paraphrase vừa đủ. Nếu đề yêu cầu “two reasons”, phải có đúng hai ý phân biệt.</p>
<div class="formula">Answer = Direct claim + 1–2 supporting details from the text</div>
<h5>2. Long Answer</h5><p>Đọc động từ mệnh lệnh: <b>describe</b> = mô tả; <b>explain</b> = nêu cơ chế/nguyên nhân; <b>compare and contrast</b> = giống + khác; <b>discuss</b> = nhiều chiều; <b>analyze</b> = tách yếu tố + chỉ quan hệ.</p>
<h5>3. Cấu trúc 3–5 câu hiệu quả</h5><p>Câu 1 trả lời thesis trực tiếp. Câu 2–4 triển khai evidence. Câu cuối tổng hợp/ảnh hưởng nếu cần.</p>
<h5>4. Evidence phải khớp passage</h5><p>Không thêm số liệu/chi tiết ngoài nguồn. Test 2 yêu cầu Section 2–3 “derived strictly from the text provided”.</p>
<div class="special"><b>Compare/contrast:</b> dùng whereas, while, in contrast, both, however. <b>Cause–effect:</b> because, therefore, leading to, as a result.</div>`,[
D(['Question asks “List two reasons”. Best response should…','Question asks “Identify three benefits”. You should…','For a 5-mark short answer…','When asked “why”…','When asked “what role”…'],['give the exact requested number of text-based points','write a long unrelated essay','use outside facts','repeat the question only'],'A','Bám số lượng ý và passage.'),
D(['“Compare and contrast” requires…','A comparison task should…','For ordinary vs wealthy women…','For two scientific examples…','For benefits vs stress…'],['similarities/differences or clear contrasts','only one side','a dictionary definition','no linking words'],'A','Compare/contrast cần đối chiếu có tổ chức.'),
D(['“Explain” usually requires…','To explain beach erosion…','To explain tape injury…','To explain optimism bias effect…','To explain education evolution…'],['mechanism/reason + result','a title only','one isolated noun','outside opinion only'],'A','Explain phải nêu tại sao/như thế nào và kết quả.'),
D(['A strong long answer begins with…','Best first sentence for a 10-mark response…','Before adding evidence, first…','A clear paragraph should first…','The opening should…'],['a direct thesis answering the question','an unrelated story','a dictionary list','a rhetorical question only'],'A','Mở bài ngắn, trả lời trực tiếp yêu cầu.'),
D(['Evidence should come from…','For Test 2 Section 3, support points with…','When a passage gives 20%…','When the source says “steep slopes”…','When the source names silicone…'],['the provided text','personal memory','social media','a guessed fact'],'A','Nguồn yêu cầu reasoning strictly from the text.'),
D(['Best final check before submitting…','Before pressing Submit…','For a 3–5 sentence answer…','For a 10-mark response…','For short answer marking…'],['verify every required part is answered','add unrelated facts','remove all evidence','ignore key terms'],'A','Kiểm tra command word, số ý, evidence và tính đầy đủ.')])
];
